### ISSUE TITLE
Unable to unbox with truffle

### ISSUE THREAD

**Issue by socialcode-rob1** [smartcontractkit/chainlink#1365]
When attempting to **Create a Chainlinked Project**, I receive an error that the project doesn't exist.  
Instruction ref: https://docs.chain.link/docs/create-a-chainlinked-project

```
$ truffle unbox smartcontractkit/chainlink
Downloading...
Error: Truffle Box at URL https://github.com/smartcontractkit/chainlink doesn't exist. If you believe this is an error, please contact Truffle support.
    at Request._callback (.../.config/yarn/global/node_modules/truffle/build/webpack:/~/truffle-box/lib/utils/unbox.js:50:1)
    at Request.self.callback (.../.config/yarn/global/node_modules/truffle/build/webpack:/~/request/request.js:185:1)
    at Request.emit (events.js:200:13)
    at Request.<anonymous> (.../.config/yarn/global/node_modules/truffle/build/webpack:/~/request/request.js:1157:1)
    at Request.emit (events.js:200:13)
    at IncomingMessage.<anonymous> (.../.config/yarn/global/node_modules/truffle/build/webpack:/~/request/request.js:1079:1)
    at Object.onceWrapper (events.js:288:20)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

This might be a documentation error rather than a project error.

Truffle v4.1.11

**Comment by thodges-gh** [comment]
Hi @socialcode-rob1! I think you'll just need to update your version of Truffle to 5+.

**Comment by socialcode-rob1** [comment]
Upgraded to Truffle v5.0.22. 
I'm no longer having an issue with finding Truffle Box.
