### ISSUE TITLE
Error during project build on MacOS

### ISSUE THREAD

**Issue by rafarocha** [smartcontractkit/chainlink#1367]
At the end of the `make install` log stack, indicated below, I got some errors regarding `node-gyp` and `node-pre-gyp`. [The complete log can be viewed here](https://gist.github.com/rafarocha/5420ac4e568f0825277e75cb7bda0d3d#try-4).

Build done in development branch, commit 6215610277a5ae23620f01cc6bd7706e73d01f7e (HEAD -> develop, origin / develop, origin / HEAD)

### System Information
- Ethereum client (Geth/Parity) and version: Geth/v1.8.27-stable-4bcc0a37/linux-amd64/go1.11.9
- Go version: 1.12.6 darwin/amd64
- Host OS: High Sierra 10.13.6

### Environment Variables
Not applicable 

### Additional Information
```
20 warnings and 6 errors generated.
make[1]: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command \"/usr/local/Cellar/node/12.3.1/bin/node\" \"/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=4\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.3.1/bin/node /Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command \"/usr/local/Cellar/node/12.3.1/bin/node\" \"/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents
node-pre-gyp ERR! node -v v12.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/12.3.1/bin/node /Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
20 warnings and 6 errors generated.
make[1]: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command \"/usr/local/Cellar/node/12.3.1/bin/node\" \"/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=4\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/rocha/go/src/github.com/smartcontractkit/chainlink/node_modules/fsevents
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
make: *** [yarndep] Error 1
```

**Comment by thodges-gh** [comment]
Hi @rafarocha! I updated the [Development Setup Guide](https://github.com/smartcontractkit/chainlink/wiki/Development-Setup-Guide) today to hopefully make the process a bit more streamlined. I tested it out on a fresh Ubuntu 18.04 install but I don't have a Mac to try it on if you want to give it a shot now.

**Comment by rafarocha** [comment]
successfully after setup node version 10.15, this [log build](https://gist.github.com/rafarocha/5420ac4e568f0825277e75cb7bda0d3d#try-5) ... thanks @thodges-gh
