### ISSUE TITLE
RequestError: Error: connect ETIMEDOUT 199.59.149.136:443

### ISSUE THREAD

**Issue by Shirley-Ji** [smartcontractkit/chainlink#1847]
Hi guys,

I hit this "RequestError: Error: connect ETIMEDOUT 199.59.149.136:443", any idea?

√ Preparing to download
× Downloading
RequestError: Error: connect ETIMEDOUT 199.59.149.136:443
    at new RequestError (C:\Users\abc\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request-promise-core\lib\errors.js:14:1)
    at Request.plumbing.callback (C:\Users\abc\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request-promise-core\lib\plumbing.js:87:1)
    at Request.RP$callback [as _callback] (C:\Users\abc\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request-promise-core\lib\plumbing.js:46:1)
    at self.callback (C:\Users\abc\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:185:1)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (C:\Users\abc\AppData\Roaming\npm\node_modules\truffle\build\webpack:\~\request\request.js:881:1)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Truffle v5.0.42 (core: 5.0.42)
Node v10.15.3

My dev environment is Windows.

**Comment by thodges-gh** [comment]
I'm assuming this is occurring when running `truffle unbox smartcontractkit/chainlink`? Are you using a proxy to connect to the internet? It may be a problem with NPM, as that's all that step is really doing (`npm install`).

**Comment by Shirley-Ji** [comment]
yes, it might be due to the network issue, I've tried many proxies, and found if the VPN timeout is within 50ms, then I could unbox it successfully. Thanks very much! close it.
