### ISSUE TITLE
exited with code 1

### ISSUE THREAD

**Issue by sgarciafer** [smartcontractkit/chainlink#4]
After running the Docker container with this command:
`docker run -t --env-file=.env smartcontract/smartoracle`

All seem good, worker, web and clock get a pid, but after some lines of output I get this error: 

```
15:27:21 worker.1 | /usr/local/bundle/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
15:27:21 worker.1 | /usr/local/bundle/gems/delayed_job-4.0.6/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'
15:27:21 worker.1 | /usr/local/bundle/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
15:27:21 worker.1 | Tasks: TOP => jobs:work
15:27:21 worker.1 | (See full trace by running task with --trace)
15:27:21 worker.1 | exited with code 1
15:27:21 system   | sending SIGTERM to all processes
15:27:21 web.1    | [8] - Gracefully shutting down workers...
15:27:21 clock.1  | terminated by SIGTERM
15:27:21 web.1    | [8] === puma shutdown: 2017-09-29 15:27:21 +0000 ===
15:27:21 web.1    | [8] - Goodbye!
15:27:21 web.1    | exited with code 0
```
Technical details:
Ubuntu 16.04
Default repos updated && upgraded.

**Comment by sgarciafer** [comment]
solved after installing dependencies (ethereum & cmake) not sure which of those solved the issue though.
