### ISSUE TITLE
[DEVEL] FMv2 Segfault in getLogsToSend

### ISSUE THREAD

**Issue by aphyr** [smartcontractkit/chainlink#4434]
**Description**

Chainlink can segfault due to an invalid memory address or nil pointer dereference when running FMv2 jobs.

**Your Environment**

This occurs in Jepsen testing, with one bootstrap, Geth in dev mode, and eight oracles, all running Debian 10, with the following tuning parameters:

```
{:upkeep-count 3,
 :geth-version "1.9.22-c71a7e26",
 :contract nil,
 :prototype-version "a336bde35bbb8011e725d97f31f669f2fecaf1fa",
 :source-count 1,
 :env {"FEATURE_OFFCHAIN_REPORTING" "true",
       "ETH_GAS_BUMP_WEI" "5000000000",
       "SECURE_COOKIES" "false",
       "CHAINLINK_TLS_HOST" "",
       "ETH_GAS_BUMP_THRESHOLD" "12",
       "P2P_LISTEN_PORT" 12000,
       "ROOT" "./clroot",
       "JOB_PIPELINE_PARALLELISM" 16,
       "REAPER_EXPIRATION" "240h0m0s",
       "CHAINLINK_TLS_PORT" "0",
       "DATABASE_TIMEOUT" "",
       "CLIENT_NODE_URL" "http://localhost:6688",
       "DATABASE_URL" "postgresql://chainlink:chainlinkpw@localhost:5432/chainlinkdb?sslmode=disable",
       "LOG_LEVEL" "debug",
       "LOG_SQL_MIGRATIONS" "false",
       "EXPLORER_URL" "",
       "ETH_CHAIN_ID" 1337,
       "GAS_UPDATER_ENABLED" "true",
       "CHAINLINK_TX_ATTEMPT_LIMIT" "10",
       "MINIMUM_REQUEST_EXPIRATION" "300",
       "ALLOW_ORIGINS" "*",
       "ENABLE_BULLETPROOF_TX_MANAGER" "true",
       "MAX_RPC_CALLS_PER_SECOND" "500",
       "P2P_ANNOUNCE_PORT" 12000,
       "ORM_MAX_OPEN_CONNS" 20,
       "CHAINLINK_DEV" "true",
       "SESSION_TIMEOUT" "1h0m0s",
       "P2P_ANNOUNCE_IP" "192.168.122.110",
       "LOG_TO_DISK" "false",
       "DEFAULT_HTTP_ALLOW_UNRESTRICTED_NETWORK_ACCESS" "true",
       "ETH_URL" "ws://n1:8546/",
       "JSON_CONSOLE" "false",
       "LINK_CONTRACT_ADDRESS" "0xda2d1bd7db5d6d9f7a2e41a19b654be6cb48c0a7",
       "CHAINLINK_PORT" 6688,
       "LOG_SQL" "false",
       "CHAINLINK_TLS_REDIRECT" "false",
       "MIN_INCOMING_CONFIRMATIONS" "1",
       "ETH_GAS_PRICE_DEFAULT" "4000000000",
       "P2P_PEERSTORE_WRITE_INTERVAL" "2s",
       "MINIMUM_CONTRACT_PAYMENT" "0",
       "MIN_OUTGOING_CONFIRMATIONS" "2"},
 :chainlink-versions "94c60e2c0193cb51dbd6dc0a5e2753acdee67ff5",
 :datasource-latency 0,
 :go-version "1.16.3"}
```

**Basic Information**

We're running with ten FMv2 jobs here, which occasionally results in a node crashing with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12e90d4]

goroutine 487 [running]:
github.com/smartcontractkit/chainlink/core/services/log.(*logPool).getLogsToSend(0xc0005ab980, 0x0, 0x1, 0x32, 0x203ada8, 0x0, 0xc0023db958)
	/opt/chainlink/chainlink-build/core/services/log/pool.go:26 +0x54
github.com/smartcontractkit/chainlink/core/services/log.(*broadcaster).onNewHeads(0xc000e5e160)
	/opt/chainlink/chainlink-build/core/services/log/broadcaster.go:324 +0x408
github.com/smartcontractkit/chainlink/core/services/log.(*broadcaster).eventLoop(0xc000e5e160, 0xc000d06720, 0xc002ebcfc0, 0xc000d06700, 0x0, 0x0)
	/opt/chainlink/chainlink-build/core/services/log/broadcaster.go:272 +0x569
github.com/smartcontractkit/chainlink/core/services/log.(*broadcaster).startResubscribeLoop(0xc000e5e160)
	/opt/chainlink/chainlink-build/core/services/log/broadcaster.go:246 +0x391
created by github.com/smartcontractkit/chainlink/core/services/log.(*broadcaster).awaitInitialSubscribers
	/opt/chainlink/chainlink-build/core/services/log/broadcaster.go:167 +0x1aa
```

**Steps to Reproduce**

With the Chainlink Jepsen test version bd8856aa77c5a5f8940c576ed4f5fb3b00948694, try:

```
lein run test --nodes-file /home/aphyr/nodes -w fmv2 --write-rate 1 --read-rate 1 --time-limit 90 --job-count 10 --test-count 20
```

This doesn't crash every time--I can try to narrow down parameters that make it crash more frequently, if you like!

**Comment by aphyr** [comment]
Here are full node logs from a crashing test run: 
[20210518T095447.000-0400.zip](https://github.com/smartcontractkit/chainlink/files/6501914/20210518T095447.000-0400.zip)

**Comment by ZakAyesh** [comment]
Thanks for making this issue, and providing the logs. It is being investigated!

**Comment by samsondav** [comment]
Fixed a while ago.
