### ISSUE TITLE
[NODE] Chainlink node goes down (“panic: runtime error: slice bounds out of range [:32] with capacity 0”)

### ISSUE THREAD

**Issue by mathepp** [smartcontractkit/chainlink#5097]
**Description**
When some kind of job spec Version 1 that uses EthTx core adapter, and when a bytes encode is used, it fails and drops down the node. The node (version 0.10.14) is stopped and it doesn’t run again. 

**Basic Information**

Jobspec:
```
{
    "name": "test getipfs image",
    "initiators": [
        {
            "type": "web"
        }
    ],
  "tasks": [
    {
      "type": "httpget",
      "params": {
                "get": "https://ipfs.io/ipfs/QmZgsvrA1o1C8BGCrx6mHTqR1Ui1XqbCrtbMVrRLHtuPVD?filename=big-api-response.json",
                "path": "image"
      }
    },
    {
      "type": "jsonparse"
    },
    {
      "type": "resultcollect"
    },
    {
      "type": "ethtx",
      "confirmations": 1,
      "params": {
                "address": "0xD4288993Eaaa436d21D2478C5a6d6bAa27Db02bE",
                "functionSelector": "setStateHashIPFScid()",
                "abiEncoding": [
                      "bytes"
                 ]
      }
    }
  ]
}
```

Console Log:
```
2021-09-14T23:45:50Z [DEBUG] http adapter finished after 159.581875ms           utils/http.go:158       statusCode=200 timeElapsedSeconds=0.159581875
2021-09-14T23:45:50Z [DEBUG] Executed task httpget                              services/run_executor.go:102 elapsed=0.159775792 input_amount=0 jobID=1817e352f24e43e684256dde2cd359c7 runID=10af3942-81df-4678-8d37-7b11cce776bb status=in_progress task=907599fb-5de9-4d06-9f1f-5f35159a5119
2021-09-14T23:45:50Z [DEBUG] Executed task jsonparse                            services/run_executor.go:102 elapsed=0.000084618 input_amount=0 jobID=1817e352f24e43e684256dde2cd359c7 runID=10af3942-81df-4678-8d37-7b11cce776bb status=in_progress task=85d74782-207a-4862-a91a-a4a093a9f89b
2021-09-14T23:45:50Z [INFO]  GET /v2/runs                                       web/router.go:452       clientIP=::1 latency=12.10412ms method=GET path=/v2/runs query=jobSpecId=1817e352f24e43e684256dde2cd359c7&page=1&size=5&sort=-createdAt servedAt=2021-09-14 23:45:50 status=200
2021-09-14T23:45:50Z [DEBUG] Executed task resultcollect                        services/run_executor.go:102 elapsed=0.000094737 input_amount=0 jobID=1817e352f24e43e684256dde2cd359c7 runID=10af3942-81df-4678-8d37-7b11cce776bb status=in_progress task=278d7834-9dbf-47d4-9dfc-5a82f82697e7
2021-09-14T23:45:50Z [DEBUG] EthTx: creating eth tx for bptxm                   adapters/eth_tx.go:77   jobID=1817e352f24e43e684256dde2cd359c7 runID=10af3942-81df-4678-8d37-7b11cce776bb runRequestRequestID=<nil> runRequestTxHash=<nil> type=web
panic: runtime error: slice bounds out of range [:32] with capacity 0

goroutine 1908 [running]:
github.com/smartcontractkit/chainlink/core/adapters.(*EthTx).insertEthTx(0xc0026f3d60, 0x2f4d8ef92dbbe3b7, 0xa9fb8ec79aae4db9, 0x0, 0x0, 0x7846df814239af10, 0xbb76e7cc117b378d, 0xe6434ef252e31718, 0xc759d32cde6d2584, 0x1, ...)
    /chainlink/core/adapters/eth_tx.go:137 +0x1345
github.com/smartcontractkit/chainlink/core/adapters.(*EthTx).Perform(0xc0026f3d60, 0x7846df814239af10, 0xbb76e7cc117b378d, 0xe6434ef252e31718, 0xc759d32cde6d2584, 0x1, 0x5, 0xc0015d92c0, 0x1c9, 0x0, ...)
    /chainlink/core/adapters/eth_tx.go:88 +0x9a6
github.com/smartcontractkit/chainlink/core/services.(*runExecutor).executeTask(0xc001225ec0, 0xc002644800, 0x2f4d8ef92dbbe3b7, 0xa9fb8ec79aae4db9, 0x7846df814239af10, 0xbb76e7cc117b378d, 0x5, 0x0, 0x0, 0x0, ...)
    /chainlink/core/services/run_executor.go:161 +0x6f6
github.com/smartcontractkit/chainlink/core/services.(*runExecutor).Execute(0xc001225ec0, 0x7846df814239af10, 0xbb76e7cc117b378d, 0x2, 0x2)
    /chainlink/core/services/run_executor.go:95 +0x7de
github.com/smartcontractkit/chainlink/core/services.(*runQueue).Run.func1(0xc001252900, 0x7846df814239af10, 0xbb76e7cc117b378d, 0xc0026d44b0, 0x24)
    /chainlink/core/services/run_queue.go:120 +0x92
created by github.com/smartcontractkit/chainlink/core/services.(*runQueue).Run
    /chainlink/core/services/run_queue.go:116 +0xeb
```

- Network: Kovan
- Blockchain Client:  external ETH_URL=wss://kovan.infura.io/ws/v3/[api]
- Go Version: [e.g. v1.12]
- Operating System: ubuntu hirsute
- Commit: Starting Chainlink Node 0.10.14 at commit 8160d7726d778b5c425e4b56af30b76cbc6d222d cmd/local_client.go:63  InstanceUUID=6c9e6be3-0947-4769-8f2d-00afefab644d SHA=8160d7726d778b5c425e4b56af30b76cbc6d222d Version=0.10.14 id=boot
- Hosting Provider:  Vultr
- Startup Command: "cd ~/.chainlink-kovan14test && docker run -p 6687:6688 --name kovan-primary-14-test -v ~/.chainlink-kovan14test:/chainlink -it  --env-file=.env smartcontract/chainlink:0.10.14 local n -p /chainlink/.password -a /chainlink/.api"

**Environment Variables**

```
ALLOW_ORIGINS
*

BALANCE_MONITOR_ENABLED
true

BLOCK_BACKFILL_DEPTH
10

BLOCK_BACKFILL_SKIP
false

CHAINLINK_DEV
false

CHAINLINK_PORT
6688

CHAINLINK_TLS_HOST
CHAINLINK_TLS_PORT
0

CHAINLINK_TLS_REDIRECT
false

CLIENT_NODE_URL
http://localhost:6688

DATABASE_BACKUP_FREQUENCY
3600000000000

DATABASE_BACKUP_MODE
none

DATABASE_MAXIMUM_TX_DURATION
1800000000000

DATABASE_TIMEOUT
0s

DEFAULT_HTTP_LIMIT
32768

DEFAULT_HTTP_TIMEOUT
15s

ENABLE_EXPERIMENTAL_ADAPTERS
false

ENABLE_LEGACY_JOB_PIPELINE
true

ETH_BALANCE_MONITOR_BLOCK_DELAY
1

ETH_CHAIN_ID
42

ETH_DISABLED
false

ETH_FINALITY_DEPTH
50

ETH_GAS_BUMP_THRESHOLD
3

ETH_GAS_BUMP_TX_DEPTH
10

ETH_GAS_BUMP_WEI
5000000000

ETH_GAS_LIMIT_DEFAULT
500000

ETH_GAS_LIMIT_TRANSFER
21000

ETH_GAS_PRICE_DEFAULT
20000000000

ETH_HEAD_TRACKER_HISTORY_DEPTH
100

ETH_HEAD_TRACKER_MAX_BUFFER_SIZE
3

ETH_HTTP_URL
ETH_MAX_GAS_PRICE_WEI
5000000000000

ETH_SECONDARY_URLS
null

ETH_URL
wss://kovan.infura.io/ws/v3/49c109ec2e6449a1926e25bfcf0e44c7

EXPLORER_URL
FEATURE_EXTERNAL_INITIATORS
false

FEATURE_FLUX_MONITOR
true

FEATURE_OFFCHAIN_REPORTING
true

FLAGS_CONTRACT_ADDRESS
FM_DEFAULT_TRANSACTION_QUEUE_DEPTH
1

GAS_ESTIMATOR_MODE
BlockHistory

GAS_UPDATER_BLOCK_DELAY
1

GAS_UPDATER_BLOCK_HISTORY_SIZE
24

GAS_UPDATER_TRANSACTION_PERCENTILE
60

INSECURE_FAST_SCRYPT
false

JOB_PIPELINE_DB_POLL_INTERVAL
30000000000

JOB_PIPELINE_REAPER_INTERVAL
3600000000000

JOB_PIPELINE_REAPER_THRESHOLD
86400000000000

JSON_CONSOLE
false

KEEPER_DEFAULT_TRANSACTION_QUEUE_DEPTH
1

LINK_CONTRACT_ADDRESS
0xa36085F69e2889c224210F603D836748e7dC0088

LOG_LEVEL
debug

LOG_SQL
false

LOG_SQL_MIGRATIONS
true

LOG_TO_DISK
true

MAXIMUM_SERVICE_DURATION
8760h0m0s

MINIMUM_CONTRACT_PAYMENT_LINK_JUELS
1000000000000000

MINIMUM_REQUEST_EXPIRATION
300

MINIMUM_SERVICE_DURATION
0s

MIN_INCOMING_CONFIRMATIONS
3

MIN_OUTGOING_CONFIRMATIONS
2

OCR_BOOTSTRAP_CHECK_INTERVAL
20000000000

OCR_CONTRACT_TRANSMITTER_TRANSMIT_TIMEOUT
10000000000

OCR_DATABASE_TIMEOUT
10000000000

OCR_DEFAULT_TRANSACTION_QUEUE_DEPTH
1

OCR_DHT_LOOKUP_INTERVAL
10

OCR_INCOMING_MESSAGE_BUFFER_SIZE
10

OCR_NEW_STREAM_TIMEOUT
10000000000

OCR_OUTGOING_MESSAGE_BUFFER_SIZE
10

OCR_TRACE_LOGGING
true

OPERATOR_CONTRACT_ADDRESS
0x0000000000000000000000000000000000000000

P2PV2_ANNOUNCE_ADDRESSES
null

P2PV2_BOOTSTRAPPERS
null

P2PV2_DELTA_DIAL
15s

P2PV2_DELTA_RECONCILE
1m0s

P2PV2_LISTEN_ADDRESSES
null

P2P_BOOTSTRAP_PEERS
P2P_LISTEN_IP
0.0.0.0

P2P_LISTEN_PORT
P2P_NETWORKING_STACK
V1

P2P_PEER_ID
p2p_12D3KooWPMRXuBUw3zwWgpBjguX95poWt8fJbfR2kZY9PLYqQJFZ

REAPER_EXPIRATION
240h0m0s

REPLAY_FROM_BLOCK
-1

ROOT
/chainlink

SECURE_COOKIES
false

SESSION_TIMEOUT
15m0s
```

**Steps to Reproduce**
executing the job, for this I use web initialization to simplify the replication of the error.

**Comment by ZakAyesh** [comment]
Thanks for making this issue. It is being investigated!

**Comment by vnavascues** [comment]
I confirm I experienced this as well. A quick solution to reestablish the node was to finish the job (as errored) in the DB.

**Comment by samsondav** [comment]
JSON jobs are no longer supported as of 1.x and up. If this bug still persists with TOML jobs, please open a new issue.
