### ISSUE TITLE
[NODE] ethabiencode fails to encode number to int (except int256)

### ISSUE THREAD

**Issue by vnavascues** [smartcontractkit/chainlink#5545]
**Description**
Task `ethabiencode` fails to encode a number to any kind of `int` but `int256`. 

Trying to encode `1` as `int8` makes the job run fail with this error:
```sh
goroutine panicked when executing run: reflect: call of reflect.Value.OverflowUint on int8 Value
```

Encoding `1` as `int256` works as expected. 

**Basic Information**
- Chainlink node: `v0.10.15` and `v1.0.0`.

Logs:
```sh
2021-11-29T13:41:07Z [DEBUG] Initiating tasks for pipeline run of spec          pipeline/runner.go:438  job ID=136 job name=Test encode USD/USD price with ethabiencode as int8 jobID=136 uuid=bd71aaf5-a831-4604-8284-6cfb802b5f33 
2021-11-29T13:41:07Z [DEBUG] HTTP task: sending request                         pipeline/task.http.go:76 allowUnrestrictedNetworkAccess=true method=GET requestData=null url=https://min-api.cryptocompare.com/data/price?fsym=usd&tsyms=usd 
2021-11-29T13:41:07Z [DEBUG] http adapter got 200 in 37.027968ms                utils/http.go:149       statusCode=200 timeElapsedSeconds=0.037027968 
2021-11-29T13:41:07Z [DEBUG] http adapter finished after 37.199646ms            utils/http.go:158       statusCode=200 timeElapsedSeconds=0.037199646 
2021-11-29T13:41:07Z [DEBUG] HTTP task got response                             pipeline/task.http.go:88 dotID=request_usd_usd response={"USD":1} url=https://min-api.cryptocompare.com/data/price?fsym=usd&tsyms=usd 
2021-11-29T13:41:07Z [DEBUG] Pipeline task completed                            pipeline/runner.go:276  jobID=136 resultType=string resultValue={"USD":1} taskName=request_usd_usd taskType=http uuid=bd71aaf5-a831-4604-8284-6cfb802b5f33 
2021-11-29T13:41:07Z [DEBUG] Pipeline task completed                            pipeline/runner.go:276  jobID=136 resultType=float64 resultValue=1 taskName=price_parse taskType=jsonparse uuid=bd71aaf5-a831-4604-8284-6cfb802b5f33 
2021-11-29T13:41:07Z [ERROR] goroutine panicked executing run                   runtime/panic.go:965    panic=reflect: call of reflect.Value.OverflowUint on int8 Value stacktrace=goroutine 4543 [running]:
runtime/debug.Stack(0xc002526b88, 0x187e640, 0xc0020bc618)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/smartcontractkit/chainlink/core/services/pipeline.(*runner).run.func1.1(0xc004f77380, 0x2164348, 0xc0000440a0, 0xc0012a9ef0)
	/chainlink/core/services/pipeline/runner.go:264 +0x7c
panic(0x187e640, 0xc0020bc618)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
reflect.Value.OverflowUint(...)
	/usr/local/go/src/reflect/value.go:1430
github.com/smartcontractkit/chainlink/core/services/pipeline.convertToETHABIInteger(0x1805de0, 0xc001426328, 0x0, 0x8, 0x0, 0xc001426e0c, 0x4, 0x0, 0x0, 0x0, ...)
	/chainlink/core/services/pipeline/common_eth.go:265 +0x48d
github.com/smartcontractkit/chainlink/core/services/pipeline.convertToETHABIType(0x1805de0, 0xc001426328, 0x0, 0x8, 0x0, 0xc001426e0c, 0x4, 0x0, 0x0, 0x0, ...)
	/chainlink/core/services/pipeline/common_eth.go:112 +0x5d8
github.com/smartcontractkit/chainlink/core/services/pipeline.(*ETHABIEncodeTask).Run(0xc006574b40, 0x2164310, 0xc0049bbb80, 0xc0012a9e90, 0xc006a0a2e0, 0x1, 0x1, 0xc001da8300, 0xa, 0x10, ...)
	/chainlink/core/services/pipeline/task.eth_abi_encode.go:58 +0x678
github.com/smartcontractkit/chainlink/core/services/pipeline.(*runner).executeTaskRun(0xc000d6f290, 0x2164310, 0xc0049bbb80, 0x88, 0xc002e9ab40, 0x228, 0x27a74690, 0xed936cb71, 0x2df30a0, 0x0, ...)
	/chainlink/core/services/pipeline/runner.go:373 +0x267
github.com/smartcontractkit/chainlink/core/services/pipeline.(*runner).run.func1(0xc004f77380, 0x2164348, 0xc0000440a0, 0xc000d6f290, 0x2164310, 0xc0049bbb80, 0xc000238280, 0xc0067f01b8, 0x0, 0x0, ...)
	/chainlink/core/services/pipeline/runner.go:276 +0x177
created by github.com/smartcontractkit/chainlink/core/services/pipeline.(*runner).run
	/chainlink/core/services/pipeline/runner.go:261 +0x456
 
2021-11-29T13:41:07Z [DEBUG] Finished all tasks for pipeline run                pipeline/runner.go:438  jobID=136 runTime=0.038622121 specID=136 uuid=bd71aaf5-a831-4604-8284-6cfb802b5f33 
2021-11-29T13:41:07Z [INFO]  POST /v2/jobs/bd71aaf5-a831-4604-8284-6cfb802b5f33/runs web/router.go:452       clientIP=172.17.0.1 latency=49.495258ms method=POST path=/v2/jobs/bd71aaf5-a831-4604-8284-6cfb802b5f33/runs servedAt=2021-11-29 13:41:07 status=200 
2021-11-29T13:41:07Z [INFO]  GET /v2/jobs/136/runs                              web/router.go:452       clientIP=172.17.0.1 latency=6.194083ms method=GET path=/v2/jobs/136/runs query=page=1&size=5 servedAt=2021-11-29 13:41:07 status=200 

```

Job run details:

![image](https://user-images.githubusercontent.com/14769962/143878425-4f60c4af-33d6-4c45-9157-34141a389b4e.png)

**Environment Variables**
If tested with a `webhook` job set first `FEATURE_WEBHOOK_V2=true`.

**Steps to Reproduce**

Encode `1` to `int256` succeeds:

```toml
type = "webhook"
schemaVersion = 1
name = "Test encode USD/USD price with ethabiencode as int256"
maxTaskDuration = "0s"
observationSource = """
    request_usd_usd         [type="http"
                             method="GET"
                             url="https://min-api.cryptocompare.com/data/price?fsym=usd&tsyms=usd"
                             allowunrestrictednetworkaccess="true"]

    price_parse             [type="jsonparse" data="$(request_usd_usd)" path="USD"]

    encode_price            [type="ethabiencode"
                             abi="(int256 _price)"
                             data="{\\"_price\\": $(price_parse)}"]

    request_usd_usd -> price_parse -> encode_price
"""
```

Encode `1` to `int8` fails:

```toml
type = "webhook"
schemaVersion = 1
name = "Test encode USD/USD price with ethabiencode as int8"
maxTaskDuration = "0s"
observationSource = """
    request_usd_usd         [type="http"
                             method="GET"
                             url="https://min-api.cryptocompare.com/data/price?fsym=usd&tsyms=usd"
                             allowunrestrictednetworkaccess="true"]

    price_parse             [type="jsonparse" data="$(request_usd_usd)" path="USD"]

    encode_price            [type="ethabiencode"
                             abi="(int8 _price)"
                             data="{\\"_price\\": $(price_parse)}"]

    request_usd_usd -> price_parse -> encode_price
"""
```

**Additional Information**
Please let me know if this either a misinterpretation of the `ethabiencode`  or a bug (perhaps fixed in v1.0.1, or `ethabiencode2`)?

Thanks!

**Comment by makramkd** [comment]
@vnavascues thanks for filing this issue! The fix has been merged into our `develop` branch and should be in a release soon.
